package co.edu.uniquindio.gri.controller;

public class Constantes {

	public static final int LINK_GRUPLAC = 14;
	public static final int FUZZY_MATCH=95;
	
	/*
	 * Tipo de Produccion
	 */
	public static final int ID_EVALUADOR = 0;
	public static final String EVALUADOR = "ACTIVIDAD COMO EVALUADOR";
	public static final int ID_FORMACION = 1;
	public static final String FORMACION = "ACTIVIDAD DE FORMACIÓN";
	public static final int ID_APROPIACION = 2;
	public static final String APROPIACION = "APROPIACIÓN SOCIAL";
	public static final int ID_BIBLIOGRAFICA = 3;
	public static final String BIBLIOGRAFICA = "PRODUCCIÓN BIBLIOGRAFICAS";
	public static final int ID_TECNICA = 4;
	public static final String TECNICA = "PRODUCCIÓN TÉCNICAS Y TECNOLÓGICAS";
	public static final int ID_MASINFORMACION = 5;
	public static final String MASINFORMACION = "MÁS INFORMACIÓN";
	public static final int ID_ARTE = 6;
	public static final String ARTE = "PRODUCCIÓN EN ARTE";

	/*
	 * Tipo
	 */
	public static final int ID_CURSO_CORTO = 0;
	public static final String CURSO_CORTO = "CURSOS DE CORTA DURACIÓN";
	public static final int ID_TUTORIA = 1;
	public static final String TUTORIA = "TUTORIA";
	public static final int ID_JURADO_COMITE_EVALUADOR = 2;
	public static final String JURADO_COMITE_EVALUADOR = "JURADO EN COMITÉ DE EVALUACIÓN";
	public static final int ID_PARTICIPACION_COMITE_EVALUADOR = 3;
	public static final String PARTICIPACION_COMITE_EVALUADOR = "PARTICIPACIÓN EN COMITÉ DE EVALUACIÓN";
	public static final int ID_PAR_EVALUADOR = 4;
	public static final String PAR_EVALUADOR = "PAR EVALUADOR";
	public static final int ID_EDICION = 5;
	public static final String EDICION = "EDICIÓN/REVISIÓN";
	public static final int ID_EVENTO_CINTIFICO = 6;
	public static final String EVENTO_CIENTIFICO = "EVENTO CIENTÍFICO";
	public static final int ID_RED = 7;
	public static final String RED = "RED DE CONOCIMIENTO ESPECIALIZADO";
	public static final int ID_CONTENIDO_IMPRESO = 8;
	public static final String CONTENIDO_IMPRESO = "GENERACIÓN DE CONTENIDO IMPRESO";
	public static final int ID_CONTENIDO_MULTIMEDIA = 9;
	public static final String CONTENIDO_MULTIMEDIA = "GENERACIÓN DE CONTENIDO MULTIMEDIA";
	public static final int ID_CONTENIDO_VIRTUAL = 10;
	public static final String CONTENIDO_VIRTUAL = "GENERACIÓN DE CONTENIDO VIRTUAL";
	public static final int ID_ESTRATEGIA_COMUNICACION = 11;
	public static final String ESTRATEGIA_COMUNICACION = "ESTRATEGIA DE COMUNICACIÓN DEL CONOCIMIENTO";
	public static final int ID_ESTRATEGIA_PEDAGOGICA = 12;
	public static final String ESTRATEGIA_PEDAGOGICA = "ESTRATEGIA PEDAGÓGICA PARA EL FOMENTO A LA CTI";
	public static final int ID_ESPACIO_PARTICIPACION = 13;
	public static final String ESPACIO_PARTICIPACION = "ESPACIO DE PARTICIPACIÓN CIUDADANA";
	public static final int ID_ESPACIO_PARTICIPACION_CTI = 14;
	public static final String ESPACIO_PARTICIPACION_CTI = "ESPACIO DE PARTICIPACIÓN CIUDADANA CTI";
	public static final int ID_ARTICULO = 15;
	public static final String ARTICULO = "ARTICULO EN REVISTA ESPECIALIZADA";
	public static final int ID_OTRO_ARTICULO = 16;
	public static final String OTRO_ARTICULO = "OTRO ARTICULO";
	public static final int ID_LIBRO = 17;
	public static final String LIBRO = "LIBRO";
	public static final int ID_OTRO_LIBRO = 18;
	public static final String OTRO_LIBRO = "OTRO LIBRO";
	public static final int ID_CAPITULO_LIBRO = 19;
	public static final String CAPITULO_LIBRO = "CAPITULO DE LIBRO";
	public static final int ID_OTRO_CAPITULO_LIBRO = 20;
	public static final String OTRO_CAPITULO_LIBRO = "OTRO CAPITULO DE LIBRO";
	public static final int ID_ARTICULO_NO_CIENTIFICO = 21;
	public static final String ARTICULO_NO_CIENTIFICO = "ARTICULO NO CIENTÍFICO";
	public static final int ID_DOCUMENTO_TRABAJO = 22;
	public static final String DOCUMENTO_TRABAJO = "DOCUMENTO DE TRABAJO";
	public static final int ID_OTRA_PRODUCCION_BIBLIOGRAFICA = 23;
	public static final String OTRA_PRODUCCION_BIBLIOGRAFICA = "OTRA PRODUCCIÓN BIBLIOGRÁFICA";
	public static final int ID_SOFTWARE = 24;
	public static final String SOFTWARE = "SOFTWARE";
	public static final int ID_PROTOTIPO = 25;
	public static final String PROTOTIPO = "PROTOTIPO/PATENTE";
	public static final int ID_PRODUCTO_TECNOLOGICO = 26;
	public static final String PRODUCTO_TECNOLOGICO = "PRODUCTO TECNOLÓGICO";
	public static final int ID_INNOVACION_PROCESO = 27;
	public static final String INNOVACION_PROCESO = "INNOVACIÓN EN PROCESO/TÉCNICA";
	public static final int ID_TRABAJO_TECNICO = 28;
	public static final String TRABAJO_TECNICO = "TRABAJO TÉCNICO";
	public static final int ID_NORMA = 29;
	public static final String NORMA = "REGULACIÓN/NORMA";
	public static final int ID_INFORME_INVESTIGACION = 30;
	public static final String INFORME_INVESTIGACION = "INFORME DE INVESTIGACIÓN";
	public static final int ID_EMPRESA_TECNOLOGICA = 31;
	public static final String EMPRESA_TECNOLOGICA = "EMPRESA DE BASE TECNOLÓGICA";
	public static final int ID_DEMAS_TRABAJOS = 32;
	public static final String DEMAS_TRABAJOS = "DEMÁS TRABAJOS";
	public static final int ID_PROYECTO = 33;
	public static final String PROYECTO = "PROYECTO";
	public static final int ID_OBRA = 34;
	public static final String OBRA = "OBRA";
	public static final int ID_ACUERDO_LICENCIA = 35;
	public static final String ACUERDO_LICENCIA = "REGISTRO DE ACUERDO DE LICENCIA";
	public static final int ID_INDUSTRIA_CREATIVA = 36;
	public static final String INDUSTRIA_CREATIVA = "INDUSTRIA CREATIVA Y CULTURAL";
	public static final int ID_EVENTO_ARTISTICO = 37;
	public static final String EVENTO_ARTISTICO = "EVENTO ARTÍSTICO";
	public static final int ID_TALLER_CREATIVO = 38;
	public static final String TALLER_CREATIVO = "TALLER CREATIVO";
	public static final int ID_OTRA_PUBLICACION_DIVULGATIVA = 39;
	public static final String OTRA_PUBLICACION_DIVULGATIVA = "OTRA PUBLICACIÓN DIVULGATIVA";
	public static final int ID_TRADUCCION = 40;
	public static final String TRADUCCION = "TRADUCCIÓN";
	public static final int ID_TRABAJO_GRADO_P = 41;
	public static final String TRABAJO_GRADO_P = "TRABAJO DE GRADO DE PREGRADO";
	public static final int ID_TRABAJO_GRADO_M = 42;
	public static final String TRABAJO_GRADO_M = "TRABAJO DE GRADO DE MAESTRÍA";
	public static final int ID_TRABAJO_GRADO_D = 43;
	public static final String TRABAJO_GRADO_D = "TRABAJO DE GRADO DE DOCTORADO";
	public static final int ID_PROYECTO_LEY = 44;
	public static final String PROYECTO_LEY = "PROYECTO DE LEY";
	public static final int ID_GUIA_CLINICA = 45;
	public static final String GUIA_CLINICA = "GUÍA CLÍNICA";
	public static final int ID_REGLAMENTO_TECNICO = 46;
	public static final String REGLAMENTO_TECNICO = "REGLAMENTO TÉCNICO";
	public static final int ID_PLANTA_PILOTO = 47;
	public static final String PLANTA_PILOTO = "PLANTA PILOTO";
	public static final int ID_OTRO_PRODUCTO_TECNOLOGICO = 48;
	public static final String OTRO_PRODUCTO_TECNOLOGICO = "OTRO PRODUCTO TECNOLÓGICO";
	public static final int ID_INNOVACION_EMPRESARIAL = 49;
	public static final String INNOVACION_EMPRESARIAL = "INNOVACIÓN EN GESTIÓN EMPRESARIAL";
	public static final int ID_ESQUEMA_IC = 50;
	public static final String ESQUEMA_IC = "ESQUEMA DE IC";
	public static final int ID_DISEÑO_INDUSTRIAL = 51;
	public static final String DISEÑO_INDUSTRIAL = "DISEÑO INDUSTRIAL";
	public static final int ID_CONSULTORIA = 52;
	public static final String CONSULTORIA = "CONSULTORÍA/INFORME TÉCNICO";
	public static final int ID_CARTA_MAPA = 53;
	public static final String CARTA_MAPA = "CARTA/MAPA";
}
